name: Build Windows App

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # نصب کیوت
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          arch: 'win64_msvc2019_64'

      # بیلد کردن پروژه
      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"
          cmake --build build --config Release

      # آماده‌سازی فایل‌های نهایی (دیپلوی)
      - name: Deploy
        run: |
          & "${{ env.Qt6_DIR }}/bin/windeployqt.exe" --qmldir . build/Release/MyQtApp.exe --compiler-runtime

      # تحویل خروجی نهایی به شما
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-Windows
          path: build/Release/
